# Docker Compose file for Toohga (https://github.com/jarne/Toohga)

version: "3.3"

services:
  tg-mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - tg-mysql-data:/var/lib/mysql
    restart: always
  tg-redis:
    image: redis:6.2
    volumes:
      - tg-redis-data:/data
    restart: always
  tg-apache:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: tg-mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: tg-redis
      ADMIN_KEY: ${ADMIN_KEY}
    depends_on:
      - tg-mysql
      - tg-redis
    ports:
      - "8080:80"
    restart: always

volumes:
  tg-mysql-data:
    driver: local
  tg-redis-data:
    driver: local
